"""add events snapshots versioning

Revision ID: adb5dffa0529
Revises: 
Create Date: 2026-06-08 10:21:20.180239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adb5dffa0529'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neighborhoods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lng', sa.Float(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'slug', name='uq_neighborhood_city_slug')
    )
    op.create_index(op.f('ix_neighborhoods_city'), 'neighborhoods', ['city'], unique=False)
    op.create_index(op.f('ix_neighborhoods_slug'), 'neighborhoods', ['slug'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spider_name', sa.String(length=100), nullable=False),
    sa.Column('spider_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scrape_run_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('listings_found', sa.Integer(), nullable=False),
    sa.Column('listings_stored', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_runs_spider_name'), 'scrape_runs', ['spider_name'], unique=False)
    op.create_table('complexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neighborhood_id', 'slug', name='uq_complex_neighborhood_slug')
    )
    op.create_index(op.f('ix_complexes_neighborhood_id'), 'complexes', ['neighborhood_id'], unique=False)
    op.create_index(op.f('ix_complexes_slug'), 'complexes', ['slug'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('neighborhood_id', sa.Integer(), nullable=False),
    sa.Column('median_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mean_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('median_price_per_sqm', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mean_price_per_sqm', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=False),
    sa.Column('median_size_sqm', sa.Float(), nullable=True),
    sa.Column('mean_size_sqm', sa.Float(), nullable=True),
    sa.Column('median_rent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_yield_pct', sa.Float(), nullable=True),
    sa.Column('luxury_percentage', sa.Float(), nullable=True),
    sa.Column('new_build_percentage', sa.Float(), nullable=True),
    sa.Column('median_building_age', sa.Float(), nullable=True),
    sa.Column('market_health_score', sa.Float(), nullable=True),
    sa.Column('price_stability_score', sa.Float(), nullable=True),
    sa.Column('construction_activity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'neighborhood_id', name='uq_snapshot_date_neighborhood')
    )
    op.create_index(op.f('ix_market_snapshots_neighborhood_id'), 'market_snapshots', ['neighborhood_id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_snapshot_date'), 'market_snapshots', ['snapshot_date'], unique=False)
    op.create_table('raw_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=False),
    sa.Column('source_website', sa.String(length=100), nullable=False),
    sa.Column('source_listing_id', sa.String(length=255), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('spider_version', sa.String(length=20), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_website', 'source_listing_id', 'content_hash', name='uq_raw_listing_source_hash')
    )
    op.create_index(op.f('ix_raw_listings_content_hash'), 'raw_listings', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_listings_scrape_run_id'), 'raw_listings', ['scrape_run_id'], unique=False)
    op.create_index(op.f('ix_raw_listings_source_listing_id'), 'raw_listings', ['source_listing_id'], unique=False)
    op.create_index(op.f('ix_raw_listings_source_website'), 'raw_listings', ['source_website'], unique=False)
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('neighborhood_id', sa.Integer(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neighborhood_id', 'slug', name='uq_street_neighborhood_slug')
    )
    op.create_index(op.f('ix_streets_neighborhood_id'), 'streets', ['neighborhood_id'], unique=False)
    op.create_index(op.f('ix_streets_slug'), 'streets', ['slug'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=True),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_building_slug')
    )
    op.create_index(op.f('ix_buildings_complex_id'), 'buildings', ['complex_id'], unique=False)
    op.create_index(op.f('ix_buildings_neighborhood_id'), 'buildings', ['neighborhood_id'], unique=False)
    op.create_index(op.f('ix_buildings_slug'), 'buildings', ['slug'], unique=False)
    op.create_table('canonical_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duplicate_group_id', sa.String(length=36), nullable=True),
    sa.Column('listing_type', sa.Enum('SALE', 'RENT', name='listing_type_canonical', native_enum=False), nullable=True),
    sa.Column('property_type', sa.Enum('APARTMENT', 'HOUSE', 'STUDIO', 'ROOM', 'VILLA', 'LAND', 'COMMERCIAL', 'GARAGE', 'OTHER', name='property_type_canonical', native_enum=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rent_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'CHF', 'UNKNOWN', name='currency_canonical', native_enum=False), nullable=False),
    sa.Column('price_per_sqm', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.Column('complex_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('construction_year', sa.Integer(), nullable=True),
    sa.Column('building_age_category', sa.Enum('NEW', 'MODERN', 'OLD', 'UNKNOWN', name='building_age_category_canonical', native_enum=False), nullable=True),
    sa.Column('is_new_construction', sa.Boolean(), nullable=True),
    sa.Column('is_furnished', sa.Boolean(), nullable=True),
    sa.Column('heating_type', sa.Enum('CENTRAL', 'GAS', 'ELECTRIC', 'WOOD', 'NONE', 'OTHER', 'UNKNOWN', name='heating_type_canonical', native_enum=False), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_properties_building_id'), 'canonical_properties', ['building_id'], unique=False)
    op.create_index(op.f('ix_canonical_properties_city'), 'canonical_properties', ['city'], unique=False)
    op.create_index(op.f('ix_canonical_properties_complex_id'), 'canonical_properties', ['complex_id'], unique=False)
    op.create_index(op.f('ix_canonical_properties_duplicate_group_id'), 'canonical_properties', ['duplicate_group_id'], unique=False)
    op.create_index(op.f('ix_canonical_properties_neighborhood_id'), 'canonical_properties', ['neighborhood_id'], unique=False)
    op.create_index(op.f('ix_canonical_properties_street_id'), 'canonical_properties', ['street_id'], unique=False)
    op.create_table('parsed_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_listing_id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=False),
    sa.Column('spider_version', sa.String(length=20), nullable=False),
    sa.Column('source_website', sa.String(length=100), nullable=False),
    sa.Column('source_listing_id', sa.String(length=255), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('property_type', sa.Enum('APARTMENT', 'HOUSE', 'STUDIO', 'ROOM', 'VILLA', 'LAND', 'COMMERCIAL', 'GARAGE', 'OTHER', name='property_type', native_enum=False), nullable=True),
    sa.Column('listing_type', sa.Enum('SALE', 'RENT', name='listing_type', native_enum=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rent_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'CHF', 'UNKNOWN', name='currency', native_enum=False), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('neighborhood_raw', sa.String(length=255), nullable=True),
    sa.Column('street_raw', sa.String(length=255), nullable=True),
    sa.Column('complex_raw', sa.String(length=255), nullable=True),
    sa.Column('building_raw', sa.String(length=255), nullable=True),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.Column('complex_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('construction_year', sa.Integer(), nullable=True),
    sa.Column('building_age_category', sa.Enum('NEW', 'MODERN', 'OLD', 'UNKNOWN', name='building_age_category', native_enum=False), nullable=True),
    sa.Column('is_new_construction', sa.Boolean(), nullable=True),
    sa.Column('is_under_construction', sa.Boolean(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('is_furnished', sa.Boolean(), nullable=True),
    sa.Column('heating_type', sa.Enum('CENTRAL', 'GAS', 'ELECTRIC', 'WOOD', 'NONE', 'OTHER', 'UNKNOWN', name='heating_type', native_enum=False), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=True),
    sa.Column('description_original', sa.Text(), nullable=True),
    sa.Column('description_cleaned', sa.Text(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_listing_id'], ['raw_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_listings_building_id'), 'parsed_listings', ['building_id'], unique=False)
    op.create_index(op.f('ix_parsed_listings_city'), 'parsed_listings', ['city'], unique=False)
    op.create_index(op.f('ix_parsed_listings_complex_id'), 'parsed_listings', ['complex_id'], unique=False)
    op.create_index(op.f('ix_parsed_listings_neighborhood_id'), 'parsed_listings', ['neighborhood_id'], unique=False)
    op.create_index(op.f('ix_parsed_listings_raw_listing_id'), 'parsed_listings', ['raw_listing_id'], unique=False)
    op.create_index(op.f('ix_parsed_listings_scrape_run_id'), 'parsed_listings', ['scrape_run_id'], unique=False)
    op.create_index(op.f('ix_parsed_listings_source_listing_id'), 'parsed_listings', ['source_listing_id'], unique=False)
    op.create_index(op.f('ix_parsed_listings_source_website'), 'parsed_listings', ['source_website'], unique=False)
    op.create_index(op.f('ix_parsed_listings_street_id'), 'parsed_listings', ['street_id'], unique=False)
    op.create_table('normalized_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parsed_listing_id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=False),
    sa.Column('spider_version', sa.String(length=20), nullable=False),
    sa.Column('source_website', sa.String(length=100), nullable=False),
    sa.Column('source_listing_id', sa.String(length=255), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('property_type', sa.Enum('APARTMENT', 'HOUSE', 'STUDIO', 'ROOM', 'VILLA', 'LAND', 'COMMERCIAL', 'GARAGE', 'OTHER', name='property_type_norm', native_enum=False), nullable=True),
    sa.Column('listing_type', sa.Enum('SALE', 'RENT', name='listing_type_norm', native_enum=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rent_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'CHF', 'UNKNOWN', name='currency_norm', native_enum=False), nullable=False),
    sa.Column('price_per_sqm', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.Column('complex_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('construction_year', sa.Integer(), nullable=True),
    sa.Column('building_age_category', sa.Enum('NEW', 'MODERN', 'OLD', 'UNKNOWN', name='building_age_category_norm', native_enum=False), nullable=True),
    sa.Column('is_new_construction', sa.Boolean(), nullable=True),
    sa.Column('is_under_construction', sa.Boolean(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('is_furnished', sa.Boolean(), nullable=True),
    sa.Column('heating_type', sa.Enum('CENTRAL', 'GAS', 'ELECTRIC', 'WOOD', 'NONE', 'OTHER', 'UNKNOWN', name='heating_type_norm', native_enum=False), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=True),
    sa.Column('description_original', sa.Text(), nullable=True),
    sa.Column('description_cleaned', sa.Text(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocode_precision', sa.String(length=50), nullable=True),
    sa.Column('normalization_version', sa.String(length=20), nullable=False),
    sa.Column('normalized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parsed_listing_id'], ['parsed_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_listings_building_id'), 'normalized_listings', ['building_id'], unique=False)
    op.create_index(op.f('ix_normalized_listings_city'), 'normalized_listings', ['city'], unique=False)
    op.create_index(op.f('ix_normalized_listings_complex_id'), 'normalized_listings', ['complex_id'], unique=False)
    op.create_index(op.f('ix_normalized_listings_neighborhood_id'), 'normalized_listings', ['neighborhood_id'], unique=False)
    op.create_index(op.f('ix_normalized_listings_parsed_listing_id'), 'normalized_listings', ['parsed_listing_id'], unique=True)
    op.create_index(op.f('ix_normalized_listings_scrape_run_id'), 'normalized_listings', ['scrape_run_id'], unique=False)
    op.create_index(op.f('ix_normalized_listings_source_listing_id'), 'normalized_listings', ['source_listing_id'], unique=False)
    op.create_index(op.f('ix_normalized_listings_source_website'), 'normalized_listings', ['source_website'], unique=False)
    op.create_index(op.f('ix_normalized_listings_street_id'), 'normalized_listings', ['street_id'], unique=False)
    op.create_table('property_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_property_id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('LISTED', 'PRICE_REDUCED', 'PRICE_INCREASED', 'RELISTED', 'SOLD', 'REMOVED', 'STATUS_CHANGED', name='property_event_type', native_enum=False), nullable=False),
    sa.Column('old_sale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('new_sale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('old_rent_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('new_rent_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_change_pct', sa.Float(), nullable=True),
    sa.Column('source_website', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_property_id'], ['canonical_properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_events_canonical_property_id'), 'property_events', ['canonical_property_id'], unique=False)
    op.create_index(op.f('ix_property_events_event_type'), 'property_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_property_events_recorded_at'), 'property_events', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_property_events_scrape_run_id'), 'property_events', ['scrape_run_id'], unique=False)
    op.create_table('listing_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_property_id', sa.Integer(), nullable=False),
    sa.Column('normalized_listing_id', sa.Integer(), nullable=False),
    sa.Column('parsed_listing_id', sa.Integer(), nullable=False),
    sa.Column('source_website', sa.String(length=100), nullable=False),
    sa.Column('source_listing_id', sa.String(length=255), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('is_primary_source', sa.Boolean(), nullable=False),
    sa.Column('duplicate_confidence', sa.Float(), nullable=True),
    sa.Column('duplicate_match_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_property_id'], ['canonical_properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['normalized_listing_id'], ['normalized_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parsed_listing_id'], ['parsed_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_sources_canonical_property_id'), 'listing_sources', ['canonical_property_id'], unique=False)
    op.create_index(op.f('ix_listing_sources_normalized_listing_id'), 'listing_sources', ['normalized_listing_id'], unique=True)
    op.create_index(op.f('ix_listing_sources_parsed_listing_id'), 'listing_sources', ['parsed_listing_id'], unique=False)
    op.create_index(op.f('ix_listing_sources_source_listing_id'), 'listing_sources', ['source_listing_id'], unique=False)
    op.create_index(op.f('ix_listing_sources_source_website'), 'listing_sources', ['source_website'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_property_id', sa.Integer(), nullable=False),
    sa.Column('listing_source_id', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rent_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'CHF', 'UNKNOWN', name='currency_history', native_enum=False), nullable=False),
    sa.Column('price_per_sqm', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('source_website', sa.String(length=100), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_property_id'], ['canonical_properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_source_id'], ['listing_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_canonical_property_id'), 'price_history', ['canonical_property_id'], unique=False)
    op.create_index(op.f('ix_price_history_listing_source_id'), 'price_history', ['listing_source_id'], unique=False)
    op.create_index(op.f('ix_price_history_recorded_at'), 'price_history', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_price_history_recorded_at'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_listing_source_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_canonical_property_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_listing_sources_source_website'), table_name='listing_sources')
    op.drop_index(op.f('ix_listing_sources_source_listing_id'), table_name='listing_sources')
    op.drop_index(op.f('ix_listing_sources_parsed_listing_id'), table_name='listing_sources')
    op.drop_index(op.f('ix_listing_sources_normalized_listing_id'), table_name='listing_sources')
    op.drop_index(op.f('ix_listing_sources_canonical_property_id'), table_name='listing_sources')
    op.drop_table('listing_sources')
    op.drop_index(op.f('ix_property_events_scrape_run_id'), table_name='property_events')
    op.drop_index(op.f('ix_property_events_recorded_at'), table_name='property_events')
    op.drop_index(op.f('ix_property_events_event_type'), table_name='property_events')
    op.drop_index(op.f('ix_property_events_canonical_property_id'), table_name='property_events')
    op.drop_table('property_events')
    op.drop_index(op.f('ix_normalized_listings_street_id'), table_name='normalized_listings')
    op.drop_index(op.f('ix_normalized_listings_source_website'), table_name='normalized_listings')
    op.drop_index(op.f('ix_normalized_listings_source_listing_id'), table_name='normalized_listings')
    op.drop_index(op.f('ix_normalized_listings_scrape_run_id'), table_name='normalized_listings')
    op.drop_index(op.f('ix_normalized_listings_parsed_listing_id'), table_name='normalized_listings')
    op.drop_index(op.f('ix_normalized_listings_neighborhood_id'), table_name='normalized_listings')
    op.drop_index(op.f('ix_normalized_listings_complex_id'), table_name='normalized_listings')
    op.drop_index(op.f('ix_normalized_listings_city'), table_name='normalized_listings')
    op.drop_index(op.f('ix_normalized_listings_building_id'), table_name='normalized_listings')
    op.drop_table('normalized_listings')
    op.drop_index(op.f('ix_parsed_listings_street_id'), table_name='parsed_listings')
    op.drop_index(op.f('ix_parsed_listings_source_website'), table_name='parsed_listings')
    op.drop_index(op.f('ix_parsed_listings_source_listing_id'), table_name='parsed_listings')
    op.drop_index(op.f('ix_parsed_listings_scrape_run_id'), table_name='parsed_listings')
    op.drop_index(op.f('ix_parsed_listings_raw_listing_id'), table_name='parsed_listings')
    op.drop_index(op.f('ix_parsed_listings_neighborhood_id'), table_name='parsed_listings')
    op.drop_index(op.f('ix_parsed_listings_complex_id'), table_name='parsed_listings')
    op.drop_index(op.f('ix_parsed_listings_city'), table_name='parsed_listings')
    op.drop_index(op.f('ix_parsed_listings_building_id'), table_name='parsed_listings')
    op.drop_table('parsed_listings')
    op.drop_index(op.f('ix_canonical_properties_street_id'), table_name='canonical_properties')
    op.drop_index(op.f('ix_canonical_properties_neighborhood_id'), table_name='canonical_properties')
    op.drop_index(op.f('ix_canonical_properties_duplicate_group_id'), table_name='canonical_properties')
    op.drop_index(op.f('ix_canonical_properties_complex_id'), table_name='canonical_properties')
    op.drop_index(op.f('ix_canonical_properties_city'), table_name='canonical_properties')
    op.drop_index(op.f('ix_canonical_properties_building_id'), table_name='canonical_properties')
    op.drop_table('canonical_properties')
    op.drop_index(op.f('ix_buildings_slug'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_neighborhood_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_complex_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_streets_slug'), table_name='streets')
    op.drop_index(op.f('ix_streets_neighborhood_id'), table_name='streets')
    op.drop_table('streets')
    op.drop_index(op.f('ix_raw_listings_source_website'), table_name='raw_listings')
    op.drop_index(op.f('ix_raw_listings_source_listing_id'), table_name='raw_listings')
    op.drop_index(op.f('ix_raw_listings_scrape_run_id'), table_name='raw_listings')
    op.drop_index(op.f('ix_raw_listings_content_hash'), table_name='raw_listings')
    op.drop_table('raw_listings')
    op.drop_index(op.f('ix_market_snapshots_snapshot_date'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_neighborhood_id'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_complexes_slug'), table_name='complexes')
    op.drop_index(op.f('ix_complexes_neighborhood_id'), table_name='complexes')
    op.drop_table('complexes')
    op.drop_index(op.f('ix_scrape_runs_spider_name'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index(op.f('ix_neighborhoods_slug'), table_name='neighborhoods')
    op.drop_index(op.f('ix_neighborhoods_city'), table_name='neighborhoods')
    op.drop_table('neighborhoods')
    # ### end Alembic commands ###
